import Head from "next/head";
import Image from "next/image";
import HeaderNav from "../components/HeaderNav";
import Hero from "../components/Hero";
import VerticalMail from "../components/VerticalMail";
import VerticalSocials from "../components/VerticalSocials";

import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="bg-gray-800 h-[calc(100vh-64px)]">
      <Head>
        <title>mrks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <VerticalMail />
        <VerticalSocials />
      </main>
    </div>
  );
}
